services:
  mongo:
    image: mongo:latest
    container_name: mongo-user
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"
  be:
    container_name: BE
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  mongo-db:
